import { PaymentsData } from "@models/DataModels";

export const paymentInitialValues: PaymentsData = {
  id: "",
  paymentDate: "",
  amount: 0,
  quotaNumber: 0,
  paymentCycle: "",
  paymentStatus: "",
  loan: {
    id: "",
    amount: 0,
    paymentCycle: "Semanal",
    deadline: 0,
    client: {
      id: "",
      workingInformation: {
        companyName: "",
        phone: "",
        address: "",
        timeWorking: 0,
        position: "",
        bossName: "",
        bossPhone: "",
        salary: 0,
        paymentOfPayroll: "Semanal",
        otherIncome: 0,
        description: "",
      },
      bankAccount: {
        accountType: "",
        bank: "",
        name: "",
        bankingApplication: "",
        transfers: "",
        accountNumber: "",
      },
      email: "",
      fullName: "",
      typeOfIdentification: "",
      identification: "",
      phone: "",
      civilStatus: "",
      profession: "",
      address: "",
      houseNumber: "",
      sector: "",
      typeOfResidence: "",
    },
    loanState: "Pendiente",
    interest: 0,
    earnings: 0,
    firstPaymentDate: "",
    paymentSchedules: [],
    numberOfPayments: "",
    amountInterest: 0,
  },
};
